# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ec6d424788d457af5617ba0a7762a5aa642927d7907296632873b3244d5b743e3e4878ebcabbce653690fbf83b134978f7aded0dea9b86738b173fcdfecfb1f

test:
  secret_key_base: da78b3fba81bf839196c7b586bb67c1e9e7c58c5205c76175af034c61906b4c9dfd7612d33198e952c581eefea0c5140cdb3e8e137ead0b696ef5e56e0da02d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
